eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8011/eureka/
server:
  port: 8015
spring:
  application:
    name: service-zuul
logging:
  level:
    root: debug
  file: ../logs/zuul-log.log
zuul: 
  routes: 
   #注:这儿所有的path前缀将被路由后去掉，若要保留添加
   #stripPrefix: false
   ribbon-client: 
    path: /ribbon/**
    stripPrefix: false
    serviceId: service-ribbon
    sensitiveHeaders: Cookie #指定被忽略头文件列表
   test-client: 
    path: /test/**
    serviceId: service-hi
#hystrix调用方法的超时时间，默认是1000毫秒，会报超时
hystrix: 
 command: 
  default: 
   execution: 
    isolation: 
     thread: 
      timeoutInMilliseconds: 5000
#避免401无权限
management: 
 security: 
  enabled: false
    