eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8012
spring:
  application:
    name: service-hi
logging:
  level:
    root: debug
  file: ../logs/log.log