spring: 
 application: 
  name: config-server
 profiles: 
  active: dev
 cloud: 
    config:
      server:
        git:
          uri: https://github.com/fcitem/springcloud-config/
          #公开仓库不用加用户验证,输入http://localhost:8016/config-client/dev验证
          username: fcitem
          password: 
          searchPaths: config-repo
      label: master
server:
  port: 8016
management: 
 security: 
  enabled: false