spring: 
 application: 
  name: config-server
 cloud: 
    config:
      server:
        git:
          uri: https://github.com/fcitem/springcloud-config
          #公开仓库不用加用户验证
          username: fcitem
          password: 
        searchPaths: config-repo
      label: master
      enabled: true
server:
  port: 8016
management: 
 security: 
  enabled: false