eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8014
  max-http-header-size: 8192
spring:
  application:
    name: service-hi
logging:
  level:
    root: debug
  file: ../logs/test-log.log