eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

spring:
  application:
    name: service-hi
logging:
  level:
    root: debug
  file: ../logs/test-log.log