eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8011/eureka/
spring: 
  application:
    name: service-hi
  zipkin: 
    base-url: http://zipkin:8018
  sleuth: 
    sampler: 
     percentage: 1
logging:
  level:
    root: debug
  file: ../logs/test-log.log